### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by csanfilippo**
The purpose of this PR is to add the support of Swift Package Manager

### CODE REVIEW

**Review by thehung111 — APPROVED** [review]

**Comment by thehung111** [comment]
thanks for the PR :)

**Comment by csanfilippo** [comment]
Thanks @thehung111 for approving it :) .
Could you also tag the latest commit on master so that it SPM can be used without referencing "master" as the branch.
Thanks

**Comment by thehung111** [comment]
@csanfilippo i just tag with 1.11.1

**Comment by csanfilippo** [comment]
Thanks @thehung111 ! 👍

**Pull request merged**
